version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./db/db:/var/lib/postgresql/data
    env_file:
       - ./.env
    ports:
      - "5432:5432"
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh entrypoint.sh
    volumes:
      - django_static_volume:/code/staticfiles
    env_file:
       - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    restart: always
    volumes:
      - django_static_volume:/usr/src/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - ./.env
    command: serve -s build -l 3000
    depends_on:
      - web
volumes:
  db:
  django_static_volume: